"""
Baseline Batch Splitter with SHA256 Verification
=================================================
Purpose: Split geocoded baseline into 50K-record batches for staged backfill
Strategy: Chronological splits preserve date ordering, SHA256 hashes ensure integrity
Date: 2026-02-06
Author: R. A. Carucci
Version: 1.0.0

Input: CAD_ESRI_Baseline_GEO_CACHED.xlsx (~754K records with X/Y coordinates)
Output: BATCH_01.xlsx through BATCH_15.xlsx (50,000 records each)
        batch_manifest.json (SHA256 hashes, record counts, date ranges)
"""

import pandas as pd
import hashlib
import json
import sys
from pathlib import Path
from datetime import datetime
import logging

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

# Configuration
CACHED_BASELINE = r"C:\Users\carucci_r\OneDrive - City of Hackensack\13_PROCESSED_DATA\ESRI_Polished\cached\CAD_ESRI_Baseline_GEO_CACHED.xlsx"
OUTPUT_DIR = r"C:\Users\carucci_r\OneDrive - City of Hackensack\13_PROCESSED_DATA\ESRI_Polished\batches"
BATCH_SIZE = 50000
DATE_COLUMN = "TimeOfCall"  # or "Time of Call" depending on schema

def compute_file_hash(file_path):
    """
    Compute SHA256 hash of file for integrity verification.
    
    Args:
        file_path: Path to file
    
    Returns:
        str: SHA256 hash (hexadecimal)
    """
    sha256 = hashlib.sha256()
    
    with open(file_path, 'rb') as f:
        # Read in 8MB chunks for memory efficiency
        for chunk in iter(lambda: f.read(8 * 1024 * 1024), b''):
            sha256.update(chunk)
    
    return sha256.hexdigest()

def split_baseline_into_batches(baseline_file, output_dir, batch_size=50000):
    """
    Split geocoded baseline into chronological batches with manifest generation.
    
    Args:
        baseline_file: Path to cached baseline with X/Y coordinates
        output_dir: Directory to save batch files
        batch_size: Records per batch (default: 50000)
    
    Returns:
        dict: Manifest with batch metadata
    """
    baseline_path = Path(baseline_file)
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)
    
    logger.info("=" * 70)
    logger.info("BASELINE BATCH SPLITTER")
    logger.info("=" * 70)
    logger.info(f"Input: {baseline_path.name}")
    logger.info(f"Size: {baseline_path.stat().st_size / (1024**2):.2f} MB")
    logger.info(f"Batch size: {batch_size:,} records")
    logger.info("")
    
    # Step 1: Load cached baseline
    logger.info("[1] Loading cached baseline with coordinates...")
    df = pd.read_excel(baseline_path, engine='openpyxl')
    total_records = len(df)
    logger.info(f"    Total records: {total_records:,}")
    
    # Verify X/Y coordinates exist
    if 'X_Coord' not in df.columns or 'Y_Coord' not in df.columns:
        logger.error("    ERROR: X_Coord or Y_Coord columns not found!")
        logger.error("    This file must be generated by create_geocoding_cache.py first")
        sys.exit(1)
    
    coords_present = df[['X_Coord', 'Y_Coord']].notnull().all(axis=1).sum()
    logger.info(f"    Records with X/Y coordinates: {coords_present:,} ({coords_present/total_records*100:.1f}%)")
    
    # Step 2: Sort by date to ensure chronological batches
    logger.info("\n[2] Sorting records chronologically...")
    
    # Try different date column names
    date_col_candidates = ['TimeOfCall', 'Time of Call', 'CallDateTime', 'IncidentDate']
    date_col = None
    for col in date_col_candidates:
        if col in df.columns:
            date_col = col
            break
    
    if not date_col:
        logger.warning("    WARNING: No date column found for chronological sorting")
        logger.warning(f"    Checked: {date_col_candidates}")
        logger.warning("    Using existing row order")
    else:
        logger.info(f"    Sorting by: {date_col}")
        df[date_col] = pd.to_datetime(df[date_col], errors='coerce')
        df = df.sort_values(date_col)
        logger.info(f"    ✓ Sorted chronologically")
    
    # Step 3: Calculate batch count
    num_batches = (total_records + batch_size - 1) // batch_size  # Ceiling division
    logger.info(f"\n[3] Batch calculation:")
    logger.info(f"    Total records: {total_records:,}")
    logger.info(f"    Batch size: {batch_size:,}")
    logger.info(f"    Total batches: {num_batches}")
    logger.info("")
    
    # Step 4: Split and save batches
    logger.info("[4] Creating batch files...")
    
    manifest = {
        "generated": datetime.now().isoformat(),
        "source_file": str(baseline_path),
        "total_records": total_records,
        "batch_size": batch_size,
        "total_batches": num_batches,
        "batches": []
    }
    
    for batch_num in range(1, num_batches + 1):
        start_idx = (batch_num - 1) * batch_size
        end_idx = min(start_idx + batch_size, total_records)
        
        batch_df = df.iloc[start_idx:end_idx]
        batch_record_count = len(batch_df)
        
        # Generate batch filename
        batch_filename = f"BATCH_{batch_num:02d}.xlsx"
        batch_path = output_path / batch_filename
        
        # Save batch
        logger.info(f"    Creating {batch_filename}...")
        batch_df.to_excel(batch_path, index=False, engine='openpyxl')
        
        # Compute file hash
        file_hash = compute_file_hash(batch_path)
        file_size_mb = batch_path.stat().st_size / (1024**2)
        
        # Get date range
        if date_col:
            min_date = batch_df[date_col].min()
            max_date = batch_df[date_col].max()
            date_range = f"{min_date.strftime('%Y-%m-%d')} to {max_date.strftime('%Y-%m-%d')}"
        else:
            date_range = "N/A"
        
        logger.info(f"      Records: {batch_record_count:,}")
        logger.info(f"      Size: {file_size_mb:.2f} MB")
        logger.info(f"      Date range: {date_range}")
        logger.info(f"      SHA256: {file_hash[:16]}...")
        
        # Add to manifest
        manifest["batches"].append({
            "batch_number": batch_num,
            "filename": batch_filename,
            "record_count": batch_record_count,
            "start_record": start_idx + 1,  # 1-indexed for user clarity
            "end_record": end_idx,
            "date_range": date_range,
            "file_size_mb": round(file_size_mb, 2),
            "sha256_hash": file_hash
        })
    
    # Step 5: Save manifest
    logger.info("\n[5] Generating batch manifest...")
    manifest_path = output_path / "batch_manifest.json"
    with open(manifest_path, 'w') as f:
        json.dump(manifest, f, indent=2)
    
    logger.info(f"    ✓ Manifest saved: {manifest_path}")
    
    # Step 6: Summary
    total_size_mb = sum([b['file_size_mb'] for b in manifest['batches']])
    
    logger.info("")
    logger.info("=" * 70)
    logger.info("BATCH SPLITTING COMPLETE")
    logger.info("=" * 70)
    logger.info(f"Output directory: {output_path}")
    logger.info(f"Total batches:    {num_batches}")
    logger.info(f"Total records:    {total_records:,}")
    logger.info(f"Total size:       {total_size_mb:.2f} MB")
    logger.info(f"Manifest:         {manifest_path.name}")
    logger.info("=" * 70)
    logger.info("")
    logger.info("Next step: Copy batch files to server for staged backfill")
    logger.info(f"  Server path: C:\\HPD ESRI\\03_Data\\CAD\\Backfill\\Batches\\")
    logger.info("")
    logger.info("Verification tip: Check SHA256 hashes after file transfer")
    logger.info("  powershell: Get-FileHash BATCH_01.xlsx -Algorithm SHA256")
    
    return manifest

def verify_batch_integrity(batch_dir, manifest_path):
    """
    Verify all batch files match their manifest SHA256 hashes.
    
    Args:
        batch_dir: Directory containing batch files
        manifest_path: Path to batch_manifest.json
    
    Returns:
        bool: True if all hashes match, False otherwise
    """
    logger.info("")
    logger.info("=" * 70)
    logger.info("BATCH INTEGRITY VERIFICATION")
    logger.info("=" * 70)
    
    with open(manifest_path, 'r') as f:
        manifest = json.load(f)
    
    all_verified = True
    
    for batch_info in manifest['batches']:
        batch_path = Path(batch_dir) / batch_info['filename']
        
        if not batch_path.exists():
            logger.error(f"    [MISSING] {batch_info['filename']}")
            all_verified = False
            continue
        
        computed_hash = compute_file_hash(batch_path)
        expected_hash = batch_info['sha256_hash']
        
        if computed_hash == expected_hash:
            logger.info(f"    [OK] {batch_info['filename']} - Hash verified")
        else:
            logger.error(f"    [FAIL] {batch_info['filename']} - Hash mismatch!")
            logger.error(f"          Expected: {expected_hash}")
            logger.error(f"          Got:      {computed_hash}")
            all_verified = False
    
    logger.info("=" * 70)
    
    if all_verified:
        logger.info("[SUCCESS] All batch files verified ✓")
        return True
    else:
        logger.error("[FAILED] Some batch files have integrity issues")
        return False

if __name__ == "__main__":
    import argparse
    
    parser = argparse.ArgumentParser(description='Split baseline into batches for staged backfill')
    parser.add_argument('--input', default=CACHED_BASELINE, help='Path to cached baseline Excel file')
    parser.add_argument('--output-dir', default=OUTPUT_DIR, help='Output directory for batch files')
    parser.add_argument('--batch-size', type=int, default=BATCH_SIZE, help='Records per batch (default: 50000)')
    parser.add_argument('--verify', action='store_true', help='Verify batch integrity after creation')
    parser.add_argument('--verify-only', action='store_true', help='Only verify existing batches (no splitting)')
    
    args = parser.parse_args()
    
    if args.verify_only:
        # Verify existing batches
        manifest_path = Path(args.output_dir) / "batch_manifest.json"
        if not manifest_path.exists():
            logger.error(f"ERROR: Manifest not found: {manifest_path}")
            sys.exit(1)
        
        verified = verify_batch_integrity(args.output_dir, manifest_path)
        sys.exit(0 if verified else 1)
    
    # Verify input file exists
    if not Path(args.input).exists():
        logger.error(f"ERROR: Cached baseline not found: {args.input}")
        logger.error("Run create_geocoding_cache.py first to generate cached baseline")
        sys.exit(1)
    
    # Run batch splitting
    try:
        manifest = split_baseline_into_batches(
            args.input, 
            args.output_dir,
            batch_size=args.batch_size
        )
        
        # Optional verification
        if args.verify:
            manifest_path = Path(args.output_dir) / "batch_manifest.json"
            verified = verify_batch_integrity(args.output_dir, manifest_path)
            if not verified:
                logger.error("ERROR: Post-creation verification failed")
                sys.exit(1)
        
        logger.info("SUCCESS: Batch splitting complete")
        sys.exit(0)
        
    except Exception as e:
        logger.error(f"FAILED: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)
