# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2026-02-09 20:29:43
"""
    NJ_Geocode_loc = "C:\\HPD ESRI\\LawEnforcementDataManagement_New\\NJ_Geocode.loc"
    L0Calls_For_Service_4_ = "https://services1.arcgis.com/JYl0Hy0wQdiiV0qh/arcgis/rest/services/CallsForService_2153d1ef33a0414291a8eb54b938507b/FeatureServer/0"
    L0CallsForServiceStatistics_2_ = "https://services1.arcgis.com/JYl0Hy0wQdiiV0qh/arcgis/rest/services/CallsForServiceStats_af933257473d49e2b4bd84f028a1c0b5/FeatureServer/0"
    Input_Time_Format = "yyyy-MM-DD HH:mm:ss"
    finalcalltable_3_ = "C:\\HPD ESRI\\LawEnforcementDataManagement_New\\LawEnforcementDataManagement.gdb\\finalcalltable"
    CFStable_4_ = "C:\\HPD ESRI\\LawEnforcementDataManagement_New\\LawEnforcementDataManagement.gdb\\CFStable"
    Field_Type = "DOUBLE"
    CFStable = "C:\\HPD ESRI\\LawEnforcementDataManagement_New\\LawEnforcementDataManagement.gdb\\CFStable"
    PolicePosts = "C:\\HPD ESRI\\LawEnforcementDataManagement_New\\LawEnforcementDataManagement.gdb\\PolicePosts"
    L0Beat = "https://services1.arcgis.com/JYl0Hy0wQdiiV0qh/arcgis/rest/services/Beat_3d1d69cc0aef4bcd89c57a3b51f5996d/FeatureServer/0"
    L0Calls_For_Service_3_ = "https://services1.arcgis.com/JYl0Hy0wQdiiV0qh/arcgis/rest/services/CallsForService_2153d1ef33a0414291a8eb54b938507b/FeatureServer/0"
    Sheet1_ = "\\\\HPD2022LawSoft\\C$\\Program Files\\FileMaker\\FileMaker Server\\Data\\Documents\\ESRI\\ESRI_CADExport.xlsx\\Sheet1$"

    # Process: Truncate Table (TruncateTable) (management)
    Truncated_Table = arcpy.management.TruncateTable(in_table=finalcalltable_3_)[0]

    # Process: Truncate Table (3) (TruncateTable) (management)
    Truncated_Table_3_ = arcpy.management.TruncateTable(in_table=CFStable_4_)[0]

    # Process: Table Select (TableSelect) (analysis)
    tempcalls_selection = "C:\\HPD ESRI\\LawEnforcementDataManagement_New\\LawEnforcementDataManagement.gdb\\tempcalls_selection"
    if Truncated_Table and Truncated_Table_3_:
        arcpy.analysis.TableSelect(in_table=Input_Spreadsheet.__str__().format(**locals(),**globals())if isinstance(Input_Spreadsheet, str) else Input_Spreadsheet, out_table=tempcalls_selection, where_clause="Time_Of_Call IS NOT NULL AND Incident NOT IN ('Assist Own Agency (Backup)', 'assist Own Agency (Backup)') And Disposition NOT IN ('Assisted', 'assisted', 'c', 'canceled', 'Canceled', 'Cancelled')")

    # Process: Convert Call Date Field (ConvertTimeField) (tbx1)
    if Truncated_Table and Truncated_Table_3_:
        TransformedCallData_5_ = ConvertTimeField(Input_Time_Format=Input_Time_Format, Input_Time_Field="Time_of_Call", Output_Time_Field_Name="calldate", Input_Table=tempcalls_selection)[0]

    # Process: Calculate Field (CalculateField) (management)
    if Truncated_Table and Truncated_Table_3_:
        tempcalls_TableSelect1_2_ = arcpy.management.CalculateField(in_table=TransformedCallData_5_, field="FullAddress2", expression="iif(left(trim($feature.FullAddress2),1)=='&'||left(trim($feature.FullAddress2),1)==',',trim(Mid($feature.FullAddress2,2)),trim($feature.FullAddress2))", expression_type="ARCADE")[0]

    # Process: Calculate Field (2) (CalculateField) (management)
    if Truncated_Table and Truncated_Table_3_:
        tempcalls_selection_2_ = arcpy.management.CalculateField(in_table=tempcalls_TableSelect1_2_, field="How_Reported", expression="   $feature.How_Reported", expression_type="ARCADE")[0]

    # Process: Convert Dispatch Date Field (ConvertTimeField) (tbx1)
    if Truncated_Table and Truncated_Table_3_:
        TransformedCallData_3_ = ConvertTimeField(Input_Time_Format=Input_Time_Format, Input_Time_Field="Time_Dispatched", Output_Time_Field_Name="dispatchdate", Input_Table=tempcalls_selection_2_)[0]

    # Process: Convert Enroute Date Field (ConvertTimeField) (tbx1)
    if Truncated_Table and Truncated_Table_3_:
        TransformedCallData_4_ = ConvertTimeField(Input_Time_Format=Input_Time_Format, Input_Time_Field="Time_Out", Output_Time_Field_Name="enroutedate", Input_Table=TransformedCallData_3_)[0]

    # Process: Convert Cleared Date Field (ConvertTimeField) (tbx1)
    if Truncated_Table and Truncated_Table_3_:
        TransformedCallData_6_ = ConvertTimeField(Input_Time_Format=Input_Time_Format, Input_Time_Field="Time_In", Output_Time_Field_Name="cleardate", Input_Table=TransformedCallData_4_)[0]

    # Process: Calculate Time to Dispatch (CalculateField) (management)
    if Truncated_Table and Truncated_Table_3_:
        TransformedCallData_10_ = arcpy.management.CalculateField(in_table=TransformedCallData_6_, field="dispatchtime", expression="""(DateDiff($feature.dispatchdate,$feature.calldate,'seconds') / 60)
""", expression_type="ARCADE", field_type=Field_Type)[0]

    # Process: Calculate Time in Queue (CalculateField) (management)
    if Truncated_Table and Truncated_Table_3_:
        TransformedCallData_9_ = arcpy.management.CalculateField(in_table=TransformedCallData_10_, field="queuetime", expression="(DateDiff($feature.enroutedate,$feature.dispatchdate,'seconds')/60)", expression_type="ARCADE", field_type=Field_Type)[0]

    # Process: Calculate Time on Call (CalculateField) (management)
    if Truncated_Table and Truncated_Table_3_:
        TransformedCallData_7_ = arcpy.management.CalculateField(in_table=TransformedCallData_9_, field="cleartime", expression="(DateDiff($feature.cleardate,$feature.enroutedate,'seconds')/60)", expression_type="ARCADE", field_type=Field_Type)[0]

    # Process: Calculate Total Response Time (CalculateField) (management)
    if Truncated_Table and Truncated_Table_3_:
        TransformedCallData_11_ = arcpy.management.CalculateField(in_table=TransformedCallData_7_, field="responsetime", expression="$feature.dispatchtime+$feature.queuetime", expression_type="ARCADE", field_type=Field_Type)[0]

    # Process: Add Date Attributes for Call Date (AddDateAttributes) (ca)
    if Truncated_Table and Truncated_Table_3_:
        TransformedCallData_2_ = arcpy.ca.AddDateAttributes(in_table=TransformedCallData_11_, date_field="calldate", date_attributes=[["DAY_FULL_NAME", "calldow"], ["DAY_OF_WEEK", "calldownum"], ["HOUR", "callhour"], ["MONTH", "callmonth"], ["YEAR", "callyear"]])[0]

    # Process: Append (Append) (management)
    if Truncated_Table and Truncated_Table_3_:
        CFStable_3_, 